global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['200.17.87.161:8180','200.17.87.161:8181','200.17.87.161:8182','200.17.87.161:8183']
 
