global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['10.0.0.2:8180','10.0.0.2:8181','10.0.0.2:8182','10.0.0.2:8183']
 
