global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: Iroha
    static_configs:
      - targets: ['127.0.0.1:7001']
  #- job_name: 'IPFS'
   # metrics_path: '/debug/metrics/prometheus'
   # static_configs:

    #  - targets: ['10.0.0.100:5001']
